# Generated by Django 2.0.2 on 2018-11-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='followers',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
