# Generated by Django 2.0.2 on 2018-11-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userdetails_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='follow',
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('username', 'follow')},
        ),
    ]
