# Generated by Django 2.0.2 on 2018-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181115_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
