# Generated by Django 2.0.2 on 2018-11-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181115_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
