# Generated by Django 2.0.2 on 2018-11-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='tweetid',
            new_name='tweet_id',
        ),
    ]
