# Generated by Django 2.0.2 on 2018-11-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181116_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('username', 'tweet_id')},
        ),
    ]
