# Generated by Django 2.0.2 on 2018-11-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181116_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='thread',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tweets'),
        ),
        migrations.AddField(
            model_name='tweets',
            name='type',
            field=models.CharField(default='nt', max_length=2),
        ),
    ]
